iList = [
    "Akino & Saren",
    "Little Lyrical",
    "Hatsune & Shior",
    "S. Saren",
    "Lyrael",
    "Croche",
    "C. Ilya",
    "Riri",
    "C. Tamaki",
    "L. Muimi",
    "L. Nozomi",
    "H. Nanaka",
    "Ameth",
    "S. Kyouka",
    "P. Inori",
    "N. Kuuka",
    "Creditta",
    "H. Ninon",
    "O. Yuki", 
    "O. Mitsuki",
    "S. Chika", 
    "S. Nozomi",
    "S. Eriko",
    "C. Rima", 
    "C. Yui",
    "X. Saren", 
    "M. Monika",
    "A. Yori",
    "S. Kaori",
    "Anne",
    "N. Rei",
    "S. Kokkoro",
    "Neneka",
    "Homare",
    "Muimi",
    "Kyaru",
    "Kokkoro",
    "Pecorine",
    "Djeeta",
    "Rima",
    "Shizuru",
    "Jun",
    "Ilya",
    "Makoto",
    "Tomo",
    "Yukari",
    "Akino",
    "Nozomi",
    "Saren",
    "Eriko",
    "Mimi",
    "Misato"
]